# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'look.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setObjectName("label_username")
        self.verticalLayout.addWidget(self.label_username)
        self.input_username = QtWidgets.QLineEdit(self.centralwidget)
        self.input_username.setObjectName("input_username")
        self.verticalLayout.addWidget(self.input_username)
        self.label_save_location = QtWidgets.QLabel(self.centralwidget)
        self.label_save_location.setObjectName("label_save_location")
        self.verticalLayout.addWidget(self.label_save_location)
        self.btn_choose_location = QtWidgets.QPushButton(self.centralwidget)
        self.btn_choose_location.setObjectName("btn_choose_location")
        self.verticalLayout.addWidget(self.btn_choose_location)
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.label_time_remaining = QtWidgets.QLabel(self.centralwidget)
        self.label_time_remaining.setObjectName("label_time_remaining")
        self.verticalLayout.addWidget(self.label_time_remaining)
        self.label_file_count = QtWidgets.QLabel(self.centralwidget)
        self.label_file_count.setObjectName("label_file_count")
        self.verticalLayout.addWidget(self.label_file_count)
        self.btn_download = QtWidgets.QPushButton(self.centralwidget)
        self.btn_download.setObjectName("btn_download")
        self.verticalLayout.addWidget(self.btn_download)
        self.label_message = QtWidgets.QLabel(self.centralwidget)
        self.label_message.setText("")
        self.label_message.setVisible(False)
        self.label_message.setObjectName("label_message")
        self.verticalLayout.addWidget(self.label_message)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Instagram Media Downloader"))
        self.label_username.setText(_translate("MainWindow", "Instagram Username:"))
        self.label_save_location.setText(_translate("MainWindow", "Save Location:"))
        self.btn_choose_location.setText(_translate("MainWindow", "Choose Location"))
        self.label_time_remaining.setText(_translate("MainWindow", "Estimated Time Remaining: 00:00"))
        self.label_file_count.setText(_translate("MainWindow", "0 / 0 files downloaded"))
        self.btn_download.setText(_translate("MainWindow", "Download Media"))
